pull_request_rules:
  - name: squash passing PRs with automerge label
    conditions:
      - label=automerge
      - status-success=windows-latest - stable
      - status-success=Validate
    actions:
      merge:
        method: squash
  - name: delete merged branches
    conditions: []
    actions:
      delete_head_branch: {}
