pull_request_rules:
  - name: squash passing PRs with automerge label
    conditions:
      - label=automerge
      - status-success=PR / windows-latest - stable (pull_request)
      - status-success=PR / Validate (pull_request)
    actions:
      merge:
        method: squash
  - name: delete merged branches
    conditions: []
    actions:
      delete_head_branch: {}
