name: PR

on:
  push:
    '!master'

jobs:
  validate:
    name: windows-latest - stable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - uses: hecrj/setup-rust-action@v1.0.2
        with:
          rust-version: stable
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --verbose
  standardize:
    name: Standardize
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not automerging
        if: github.event.pull_request.user.login != 'jsim2010' && !contains(github.event.pull_request.labels.*.name, 'automerge')
        env:
          GITHUB_USER_LOGIN: ${{ github.event.pull_request.user.login }}
          GITHUB_LABEL_NAMES: ${{ github.event.pull_request.labels.*.name }}
        run: echo "User:" && echo "$GITHUB_USER_LOGIN" && echo "Labels:" && echo "$GITHUB_LABEL_NAMES" && return 1
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup tools
        run: cargo install cargo-readme
      - name: Standardize
        run: cargo fmt && cargo readme > README.md
      - name: Output
        run: ls
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions" && git add . && git commit -m "Standardize project" --author="Standardizer <jsim2010@gmail.com>" && git push --set-upstream origin "$GITHUB_REF"
